---
# Dynamically Generated Charts
application-manager:
  common:
    repoURL: https://github.com/uc2-io/uc2-gitops.git
    targetRevision: initial-commit
    namespace: uc2-openshift-gitops
    project: cluster-config
    destinationNamespace: uc2-openshift-gitops
    prune: true
    selfHeal: true
  charts:
    # Additional Cluster Configuration Outside of Management Stack
    cluster-configs:
      name: cluster-configs
      path: charts/application-manager
      values:
        common:
          destinationNamespace: uc2-openshift-gitops
          namespace: uc2-openshift-gitops
          project: cluster-config
          prune: true
          repoURL: https://github.com/uc2-io/uc2-gitops.git
          selfHeal: true
          targetRevision: initial-commit
        charts:
          # Ansible Runner Configuration
          ansible-runner:
            annotations:
              argocd.argoproj.io/sync-wave: "0"
            name: ansible-runner
            path: charts/ansible-runner
          # Microcert API/Ingress Configuration
          microcert-client:
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            name: microcert-client
            path: charts/microcert-client
            values:
              ansible-runner-job:
                job_ansible_playbook: ansible/microcert-api-ingress.yaml
                job_git_branch: initial-commit
                job_name: microcert-client-job
                job_namespace: ansible-runner
                job_serviceaccount: microcert
          # OpenShift OAuth Configuration
          oauth:
            annotations:
              argocd.argoproj.io/sync-wave: "0"
            name: oauth
            path: charts/oauth
            values:
              rbac:
                groups:
                  - name: cluster-admins
                    users:
                      - chris
                      - juanjo
                clusterrolebinding:
                  - name: cluster-admins-group
                    role: cluster-admin
                    subjects:
                      - apiGroup: rbac.authorization.k8s.io
                        kind: Group
                        name: cluster-admins
bootstrap:
  raw: []
