---
# Dynamically Generated Charts
application-manager:
  common:
    repoURL: https://github.com/uc2-io/uc2-gitops.git
    targetRevision: initial-commit
    namespace: uc2-openshift-gitops
    project: cluster-config
    destinationNamespace: uc2-openshift-gitops
    prune: true
    selfHeal: true
  charts:
    # Additional Cluster Configuration Outside of Management Stack
    cluster-configs:
      name: cluster-configs
      path: charts/application-manager
      values:
        common:
          destinationNamespace: uc2-openshift-gitops
          namespace: uc2-openshift-gitops
          project: cluster-config
          prune: true
          repoURL: https://github.com/uc2-io/uc2-gitops.git
          selfHeal: true
          targetRevision: initial-commit
        charts:
          # Ansible Runner Configuration
          ansible-runner:
            annotations:
              argocd.argoproj.io/sync-wave: "0"
            name: ansible-runner
            path: charts/ansible-runner
          # Configure OpenShift Internal Image Registry
          registry:
            annotations:
              argocd.argoproj.io/sync-wave: "0"
            name: registry
            path: charts/registry
          # Microcert API/Ingress Configuration
          microcert-client:
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            name: microcert-client
            path: charts/microcert-client
          # OpenShift OAuth Configuration
          oauth:
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            name: oauth
            path: charts/oauth
            values:
              rbac:
                groups:
                  - name: cluster-admins
                    users:
                      - chris
                      - cpeters
                      - juanjo
                clusterrolebinding:
                  - name: cluster-admins-group
                    role: cluster-admin
                    subjects:
                      - apiGroup: rbac.authorization.k8s.io
                        kind: Group
                        name: cluster-admins
          # Deploy Kubernetes NMState Operator
          nmstate-operator:
            name: nmstate-operator
            path: charts/operator
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            destinationNamespace: openshift-nmstate
            values:
              namespace:
                enabled: true
                namespaces:
                  - name: openshift-nmstate
              operator:
                channel: stable
                installPlanApproval: Automatic
                name: kubernetes-nmstate-operator
                source: redhat-operators
                sourceNamespace: openshift-marketplace
              operatorgroup:
                clusterScope: false
                create: true
          # Group Sync Operator
          group-sync-operator:
            name: group-sync-operator
            annotations:
              argocd.argoproj.io/sync-wave: '1'
            destinationNamespace: group-sync-operator
            path: charts/operator
            values:
              namespace:
                enabled: true
                namespaces:
                  - labels:
                      openshift.io/cluster-monitoring: "true"
                    name: group-sync-operator
              operator:
                channel: alpha
                installPlanApproval: Automatic
                name: group-sync-operator
                source: community-operators
                sourceNamespace: openshift-marketplace
              operatorgroup:
                clusterScope: false
                create: true
          # Web Terminal Operator
          web-terminal-operator:
            name: web-terminal-operator
            path: charts/operator
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            destinationNamespace: openshift-operators
            values:
              operator:
                channel: fast
                installPlanApproval: Automatic
                name: web-terminal
                source: redhat-operators
                sourceNamespace: openshift-marketplace
              operatorgroup:
                clusterScope: true
                create: false
          # Compliance Operator
          compliance-operator:
            name: compliance-operator
            path: charts/operator
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            destinationNamespace: openshift-compliance
            values:
              namespace:
                enabled: true
                namespaces:
                  - labels:
                      openshift.io/cluster-monitoring: "true"
                    name: openshift-compliance
              operator:
                channel: stable
                installPlanApproval: Automatic
                name: compliance-operator
                source: redhat-operators
                sourceNamespace: openshift-marketplace
              operatorgroup:
                clusterScope: true
                create: true
          # Deploy Group Sync
          group-sync:
            name: group-sync
            path: charts/group-sync
            annotations:
              argocd.argoproj.io/sync-wave: "2"
            destinationNamespace: group-sync-operator
          # Deploy NMState Singleton
          nmstate:
            name: nmstate
            path: charts/nmstate
            annotations:
              argocd.argoproj.io/sync-wave: "3"
          # Deploy Custom Console Links
          baseline-console-links:
            name: console-links
            path: charts/console-links
            annotations:
              argocd.argoproj.io/sync-wave: "5"
            values:
              ansible-runner-job:
                enabled: true
                jobs:
                  - ansible_extravars_json: >-
                      {"console_links":[{"name":"gitops-console-link","route_name":"openshift-gitops-argocd-server","route_namespace":"uc2-openshift-gitops","imageURL":"https://argo-cd.readthedocs.io/en/stable/assets/logo.png","section":"Baseline Applications","location":"ApplicationMenu","text":"Red Hat OpenShift GitOps (Argo CD)"}]}
                    ansible_playbook: ansible/job-console-links.yaml
                    git_branch: initial-commit
                    name: baseline-console-links
bootstrap:
  raw: []
