apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  {{- if $.Values.storagecluster_annotations }}
  annotations:
    {{- tpl (toYaml $.Values.storagecluster_annotations) $ | nindent 4 }}
    {{- if $.Values.storagecluster_use_localstorage }}
    cluster.ocs.openshift.io/local-devices: "true"
    {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- if $.Values.storagecluster_labels }}
    {{- tpl (toYaml $.Values.storagecluster_labels) $ | nindent 4 }}
  {{- end }}
  name: {{ $.Values.storagecluster_name }}
  namespace: {{ $.Values.storagecluster_namespace }}
spec:
  arbiter: {}
  enableCephTools: {{ $.Values.storagecluster_enablecephtools }}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    {{- if not $.Values.storagecluster_enabledefaultstorageclass }}
    cephBlockPools: {}
    {{- else }}
    cephBlockPools:
      defaultStorageClass: true
    {{- end }}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  mgr:
    enableActivePassive: {{ $.Values.storagecluster_mgr_enableactivepassive }}
  mirroring: {}
  {{- if $.Values.storagecluster_use_localstorage }}
  monDataDirHostPath: /var/lib/rook
  {{- else }}
  monPVCTemplate:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.storagecluster_mon_storage }}
      storageClassName: {{ $.Values.storagecluster_mon_storageclass }}
      volumeMode: Block
  {{- end }}
  {{- if $.Values.storagecluster_multus_enable }}
  network:
    provider: multus
    selectors:
      cluster: {{ $.Values.storagecluster_multus_cluster_network }}
      public: {{ $.Values.storagecluster_multus_public_network }}
  {{- end }}
  nodeTopologies: {}
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.storagecluster_storage }}
        storageClassName: {{ $.Values.storagecluster_storageclass }}
        volumeMode: Block
      status: {}
    name: ocs-deviceset-{{ $.Values.storagecluster_storageclass }}
    placement: {}
    portable: true
    preparePlacement: {}
    replica: 3
    resources: {}
  version: {{ $.Values.storagecluster_version }}
