{{- range .Values.jobs -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
  {{- end }}
  labels:
    run: {{ .name }}
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  namespace: {{ .namespace | default $.Values.job_namespace }}
spec:
  template:
    spec:
      activeDeadlineSeconds: {{ .active_deadline_seconds | default $.Values.job_active_deadline_seconds }}
      containers:
        - command:
            - /bin/bash
            - -c
            - |
              mkdir -p $GIT_LOCAL_DIRECTORY
              git clone -b $GIT_BRANCH $GIT_URL $GIT_LOCAL_DIRECTORY
              ansible-galaxy collection install -r $GIT_LOCAL_DIRECTORY/$ANSIBLE_COLLECTION_REQUIREMENTS
              ansible-playbook $GIT_LOCAL_DIRECTORY/$ANSIBLE_PLAYBOOK{{ if .ansible_extravars_json }} -e '{{ .ansible_extravars_json }}'{{ end }}
          env:
            - name: ANSIBLE_COLLECTION_REQUIREMENTS
              value: "{{ .collection_requirements | default $.Values.job_collection_requirements }}"
            - name: ANSIBLE_CONFIG
              value: "{{ .git_local_directory | default $.Values.job_git_local_directory }}/{{ .ansible_config | default $.Values.job_ansible_config }}"
            - name: ANSIBLE_PLAYBOOK
              value: "{{ .ansible_playbook }}"
            - name: GIT_BRANCH
              value: "{{ .git_branch | default $.Values.job_git_branch }}"
            - name: GIT_LOCAL_DIRECTORY
              value: "{{ .git_local_directory | default $.Values.job_git_local_directory }}"
            - name: GIT_URL
              value: "{{ .git_url | default $.Values.job_git_url }}"
          image: {{ .image | default $.Values.job_image }}
          imagePullPolicy: Always
          name: ansible-runner
          {{- if .volume_mounts }}
          volumeMounts:
            {{- tpl (toYaml .volume_mounts) $ | nindent 12 }}
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ .serviceaccount | default $.Values.job_serviceaccount }}
      serviceAccountName: {{ .serviceaccount | default $.Values.job_serviceaccount }}
      terminationGracePeriodSeconds: 30
      {{- if .volumes }}
      volumes:
        {{- tpl (toYaml .volumes) $ | nindent 8 }}
      {{- end }}
{{- end }}
