---
ansible_runner_base_image: registry.access.redhat.com/ubi8/python-38
ansible_runner_debug_pod: true
ansible_runner_external_image: quay.io/nasx/gitops-ansible-runner:latest
ansible_runner_image_stream_name: ansible-runner
ansible_runner_name: ansible-runner
ansible_runner_namespace: ansible-runner
ansible_runner_use_buildconfig: false
namespace:
  namespaces:
    - name: ansible-runner
rbac:
  clusterrole:
    - name: ansible-runner-cr
      rules:
        - apiGroups:
            - automationcontroller.ansible.com
          resources:
            - automationcontrollers
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - operator.openshift.io
          resources:
            - consoles
          verbs:
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - local.storage.openshift.io
          resources:
            - localvolumesets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
            - storage.k8s.io
          resources:
            - persistentvolumes
            - storageclass
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - '*'
          resources:
            - clusterroles
            - clusterrolebindings
            - configmaps
            - pods
            - role
            - rolebinding
            - secrets
            - serviceaccounts
            - services
          verbs:
            - '*'
        - apiGroups:
            - platform.stackrox.io
          resources:
            - securedclusters
          verbs:
            - '*'
        - apiGroups:
            - observability.open-cluster-management.io
          resources:
            - multiclusterobservabilities
          verbs:
            - '*'
        - apiGroups:
            - operator.open-cluster-management.io
          resources:
            - multiclusterhubs
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
            - extensions
          resources:
            - deployments
          verbs:
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - config.openshift.io
          resources:
            - infrastructures
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - machine.openshift.io
          resources:
            - machinesets
          verbs:
            - '*'
        - apiGroups:
            - objectbucket.io
          resources:
            - objectbucketclaims
          verbs:
            - '*'
        - apiGroups:
            - route.openshift.io
          resources:
            - routes
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - console.openshift.io
          resources:
            - consolelinks
          verbs:
            - '*'
  clusterrolebinding:
    - name: ansible-runner-crb
      role: ansible-runner-cr
      subjects:
        - kind: ServiceAccount
          name: ansible-runner-sa
          namespace: ansible-runner
  sa:
    - name: ansible-runner-sa
      namespace: ansible-runner