---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
{{- if $.Values.applicationSet }}
  applicationSet:
    {{- tpl (toYaml $.Values.applicationSet) $ | nindent 4 }}
{{- end }}
{{- if $.Values.controller }}
  controller:
    {{- tpl (toYaml $.Values.controller) $ | nindent 4 }}
{{- end }}
{{- if $.Values.grafana }}
  grafana:
    {{- tpl (toYaml $.Values.grafana) $ | nindent 4 }}
{{- end }}
{{- if $.Values.ha }}
  ha:
    {{- tpl (toYaml $.Values.ha) $ | nindent 4 }}
{{- end }}
{{- if $.Values.initialSSHKnownHosts }}
  initialSSHKnownHosts:
    {{- tpl (toYaml $.Values.initialSSHKnownHosts) $ | nindent 4 }}
{{- end }}
{{- if $.Values.kustomizeBuildOptions }}
  kustomizeBuildOptions: "{{ $.Values.kustomizeBuildOptions }}"
{{- end }}
{{- if $.Values.prometheus }}
  prometheus:
    {{- tpl (toYaml $.Values.prometheus) $ | nindent 4 }}
{{- end }}
{{- if $.Values.rbac }}
  rbac:
    {{- tpl (toYaml $.Values.rbac) $ | nindent 4 }}
{{- end }}
{{- if $.Values.redis }}
  redis:
    {{- tpl (toYaml $.Values.redis) $ | nindent 4 }}
{{- end }}
{{- if $.Values.repo }}
  repo:
    {{- tpl (toYaml $.Values.repo) $ | nindent 4 }}
{{- end }}
{{- if $.Values.resourceExclusions }}
  resourceExclusions: |
    {{- $.Values.resourceExclusions | nindent 4 }}
{{- end  }}
{{- if $.Values.resourceHealthChecks }}
  resourceHealthChecks: 
    {{- tpl (toYaml $.Values.resourceHealthChecks) $ | nindent 4 }}
{{- end }}
{{- if $.Values.resourceIgnoreDifferences }}
  resourceIgnoreDifferences: 
    {{- tpl (toYaml $.Values.resourceIgnoreDifferences) $ | nindent 4 }}
{{- end }}
{{- if $.Values.server }}
  server: 
    {{- tpl (toYaml $.Values.server) $ | nindent 4 }}
{{- end }}
{{- if $.Values.sso }}
  sso: 
    {{- tpl (toYaml $.Values.sso) $ | nindent 4 }}
{{- end }}
{{- if $.Values.statusBadgeEnabled }}
  statusBadgeEnabled: {{ $.Values.statusBadgeEnabled }}
{{- end }}
{{- if $.Values.tls }}
  tls: 
    {{- tpl (toYaml $.Values.tls) $ | nindent 4 }}
{{- end }}
