{{- range $.Values.nodes }}
---
apiVersion: v1
kind: Node
metadata:
{{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
{{- end }}
{{- if .labels }}
  labels:
    {{- tpl (toYaml .labels) $ | nindent 4 }}
{{- end }}
  name: {{ .name }}
{{- if .taints }}
spec:
  taints:
    {{- tpl (toYaml .taints) $ | nindent 4 }}
{{- else }}
spec: {}
{{- end }}
{{- end }}
