---
apiVersion: v2
dependencies:
  - name: common
    repository: file://../common
    version: 0.1.0
description: Sync LDAP Groups via Group Sync Operator
name: group-sync
type: application
version: 0.1.0
