apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  name: {{ $.Values.microcert_client_sa }}
  namespace: {{ $.Values.microcert_client_namespace }}
