- name: Query Cluster Console
  kubernetes.core.k8s_info:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
  register: cluster_console_results

- name: Debug cluster_console_results
  ansible.builtin.debug:
    var: cluster_console_results

- name: Set Initial List of Plugins
  ansible.builtin.set_fact:
    initial_plugins: "{{ cluster_console_results.resources[0].spec.plugins }}"

- name: Debug initial_plugins
  ansible.builtin.debug:
    var: initial_plugins

- name: Merge Lists
  ansible.builtin.set_fact:
    merged_plugin_list: >-
      {{
        (initial_plugins + additional_plugins) | unique | sort
      }}

- name: Debug merged_plugin_list
  ansible.builtin.debug:
    var: merged_plugin_list

- name: Update Cluster Console Plugin List
  kubernetes.core.k8s:
    template: console.j2
    state: present
