---
ansible-runner-job:
  jobs:
    - annotations:
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
      ansible_playbook: ansible/job-posthook-microcert-client.yaml
      git_branch: initial-commit
      name: posthook-microcert-client
      serviceaccount: microcert
      volume_mounts:
        - mountPath: "/etc/microcert/config"
          name: microcert-token
          readOnly: true
      volumes:
        - name: microcert-token
          secret:
            secretName: microcert-token
microcert_client_namespace: ansible-runner
microcert_client_sa: microcert
