{{- range .Values.storageclasses }}
---
allowVolumeExpansion: {{ .allowVolumeExpansion }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
{{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
{{- end }}
  name: {{ .name }}
parameters:
  {{- tpl (toYaml .parameters) $ | nindent 2 }}
provisioner: {{ .provisioner }}
reclaimPolicy: {{ .reclaimPolicy }}
volumeBindingMode: {{ .volumeBindingMode }}
{{- end }}
