- name: Assert console_links
  ansible.builtin.assert:
    that:
      - console_links is defined

- name: Debug links
  ansible.builtin.debug:
    var: console_links

- name: Create ConsoleLink Resources
  ansible.builtin.include_tasks:
    file: consolelink.yaml
  loop: "{{ console_links }}"
  loop_control:
    loop_var: console_link
