{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
{{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
{{- end }}
  name: {{ .name }}
  labels:
{{- if not .skip_common_labels }}  
    {{- include "common.labels.labels" $ | nindent 4 }}
{{- end }}
{{- if .labels }}
    {{- tpl (toYaml .labels) $ | nindent 4 }}
{{- end }}
{{- end }}
