apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  {{- if $.Values.central_annotations }}
  annotations:
    {{- tpl (toYaml $.Values.central_annotations) $ | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- if $.Values.central_labels }}
    {{- tpl (toYaml $.Values.central_labels) $ | nindent 4 }}
  {{- end }}
  name: {{ $.Values.central_name }}
  namespace: {{ $.Values.central_namespace }}
spec:
  central:
    db:
      isEnabled: Default
      {{- if $.Values.global.use_infra_nodes }}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      {{- end }}
      persistence:
        persistentVolumeClaim:
          claimName: {{ $.Values.central_db_claim_name }}
          size: {{ $.Values.central_db_claim_size }}
          storageClassName: {{ $.Values.central_db_claim_storage_class }}
      {{- if $.Values.global.use_infra_nodes }}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
      {{- end }}
    {{- if $.Values.central_tls_secret_name }}
    defaultTLSSecret:
      name: {{ $.Values.central_tls_secret_name }}
    {{- end }}
    exposure:
      loadBalancer:
        enabled: false
      nodePort:
        enabled: false
      route:
        enabled: {{ $.Values.central_route_enabled }}
        {{- if $.Values.central_route_host }}
        host: {{ $.Values.central_route_host }}
        {{- end }}
    notifierSecretsEncryption:
      enabled: false
    telemetry:
      enabled: true
    {{- if $.Values.global.use_infra_nodes }}
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
    {{- end }}
  egress:
    connectivityPolicy: Online
  monitoring:
    openshift:
      enabled: true
  scannerV4:
    db:
      {{- if $.Values.global.use_infra_nodes }}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      {{- end }}
      persistence:
        persistentVolumeClaim:
          claimName: {{ $.Values.scanner_v4_db_claim_name }}
          size: {{ $.Values.scanner_v4_db_claim_size }}
          storageClassName: {{ $.Values.scanner_v4_db_claim_storage_class }}
      {{- if $.Values.global.use_infra_nodes }}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
      {{- end }}
    indexer:
      {{- if $.Values.global.use_infra_nodes }}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      {{- end }}
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
      {{- if $.Values.global.use_infra_nodes }}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
      {{- end }}
    matcher:
      {{- if $.Values.global.use_infra_nodes }}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      {{- end }}
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
      {{- if $.Values.global.use_infra_nodes }}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
      {{- end }}
    scannerComponent: Enabled
  scanner:
    analyzer:
      {{- if $.Values.global.use_infra_nodes }}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      {{- end }}
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
      {{- if $.Values.global.use_infra_nodes }}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
      {{- end }}
    {{- if $.Values.global.use_infra_nodes }}
    db:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
    {{- end }}
  {{- if $.Values.central_tls_additional_ca }}
  tls:
    additionalCAs:
      - content: |
          {{- $.Values.central_tls_additional_ca | nindent 10 }}
        name: ca-bundle.crt
  {{- end }}
