{{- if $.Values.gitops_enable }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  name: {{ $.Values.gitops_default_placement_name }}
  namespace: {{ $.Values.gitops_namespace }}
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: "In"
              values:
                - OpenShift
{{- end }}
