apiVersion: v2
dependencies:
  - condition: ansible-runner-job.enabled
    name: ansible-runner-job
    repository: file://../../ansible-runner-job
    version: 0.1.0
  - name: common
    repository: file://../../common
    version: 0.1.0
description: Chart to Deploy OpenShift Data Foundation
name: odf
type: application
version: 0.1.0
