apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
  labels:
    app.kubernetes.io/managed-by: Helm
  name: policyreports.wgpolicyk8s.io
spec:
  scope: Namespaced
