---
{{- $kubeletConfigName := .Values.kubeletConfigName | required "kubeletConfigName is required." }}
{{- $machineConfigPoolSelector := .Values.machineConfigPoolSelector | required "machineConfigPoolSelector is required." }}
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  name: {{ $kubeletConfigName }}
  namespace: openshift-machine-config-operator
spec:
  autoSizingReserved: {{ .Values.autoSizingReserved }}
  {{- if .Values.kubeletConfig }}
  kubeletConfig:
    {{-  tpl (toYaml .Values.kubeletConfig) . | nindent 4 }}
  {{- end }}
  {{- if .Values.logLevel }}
  logLevel: {{ .Values.logLevel }}
  {{- end }}
  machineConfigPoolSelector:
    {{- tpl (toYaml $machineConfigPoolSelector) . | nindent 4 }}
  {{- if .Values.tlsSecurityProfile }}
  tlsSecurityProfile:
    {{- tpl (toYaml .Values.tlsSecurityProfile) . | nindent 6 }}
  {{- end }}
