apiVersion: v2
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
description: Configure OpenShift oAuth Identity Provider
name: oauth
type: application
version: 0.1.0
