apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: cluster
spec:
  defaultRoute: {{ $.Values.registry_default_route }}
  logLevel: {{ $.Values.registry_log_level }}
  managementState: {{ $.Values.registry_management_state }}
  operatorLogLevel: {{ $.Values.registry_operator_log_level }}
  replicas: {{ $.Values.registry_replicas }}
  rolloutStrategy: {{ $.Values.registry_rollout_strategy }}
  storage:
    {{- tpl (toYaml $.Values.registry_storage_config) $ | nindent 4 }}
