apiVersion: v2
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
description: Create Instance of Ansible Runner Kubernetes Job
name: ansible-runner-job
type: application
version: 0.1.0
