{{- range $.Values.nodes }}
---
apiVersion: v1
kind: Node
metadata:
{{- if .annotations }}
  annotations:
    {{- tpl (toYaml .annotations) $ | nindent 4 }}
{{- end }}
{{- if .labels }}
  labels:
    {{- tpl (toYaml .labels) $ | nindent 4 }}
{{- end }}
  name: {{ .name }}
spec: {}
{{- end }}
