- name: Create Pull Secret for ACM MultiClusterHub
  become: false
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Make Sure Variables are Defined
      ansible.builtin.assert:
        that:
          - mch_namespace is defined
          - mch_pull_secret_name is defined

    - name: Query Cluster Pull Secret
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: pull-secret
        namespace: openshift-config
      register: cluster_pull_secret

    - name: Debug cluster_pull_secret
      ansible.builtin.debug:
        var: cluster_pull_secret

    - name: Create Pull Secret for MultiClusterHub
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: v1
          data:
            .dockerconfigjson: "{{ cluster_pull_secret.resources[0].data['.dockerconfigjson'] }}"
          kind: Secret
          metadata:
            name: "{{ mch_pull_secret_name }}"
            namespace: "{{ mch_namespace }}"
          type: kubernetes.io/dockerconfigjson
        state: present
