- name: Install Sealed Secrets Controller
  become: false
  gather_facts: false
  hosts: localhost
  vars_files:
    - vault.yaml
  roles:
    - role: sealed_secrets
      tags:
        - sealed-secrets
